#!/usr/bin/env bash
# Hard gate: fail the build if a credential, private key or personal contact
# detail is tracked now or was ever committed. Patterns are hardcoded here on
# purpose -- no network, no service, no token. Phase 1 scans the working tree
# and reports file:line. Phase 2 scans every blob in history, because a secret
# deleted in a later commit is still a leaked secret.
#
# Allowlist rules live in ALLOW_* below. Keep them narrow and justify each one.
set -euo pipefail
cd "$(dirname "$0")/.."

fail=0
hit() { printf '  %s\n' "$*"; fail=1; }
section() { printf '\n%s\n' "$1"; }

# --- Patterns -----------------------------------------------------------------

# Credentials that are never legitimate in this repo.
CRED='-----BEGIN ([A-Z]+ )?PRIVATE KEY-----'
CRED+='|ghp_[A-Za-z0-9]{20,}|gho_[A-Za-z0-9]{20,}|ghs_[A-Za-z0-9]{20,}|ghr_[A-Za-z0-9]{20,}'
CRED+='|github_pat_[A-Za-z0-9_]{20,}'
CRED+='|AKIA[0-9A-Z]{16}|ASIA[0-9A-Z]{16}'
CRED+='|sk-ant-[A-Za-z0-9_-]{20,}|sk-[A-Za-z0-9]{32,}|sk_live_[A-Za-z0-9]{20,}|rk_live_[A-Za-z0-9]{20,}'
CRED+='|AIza[0-9A-Za-z_-]{35}'
CRED+='|xox[baprs]-[A-Za-z0-9-]{10,}'
CRED+='|glpat-[A-Za-z0-9_-]{20,}|dop_v1_[a-f0-9]{64}|SG\.[A-Za-z0-9_-]{22,}'
CRED+='|eyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}'
CRED+='|(postgres|postgresql|mysql|mongodb\+srv|mongodb|redis|amqp)://[^[:space:]/]*:[^[:space:]@]+@'

# Assignment of a literal secret, e.g.  apiKey = "hunter2"
ASSIGN='(password|passwd|pwd|pass|secret|api[_-]?key|apikey|auth[_-]?token|access[_-]?token|private[_-]?key|client[_-]?secret|mnemonic|seed[_-]?phrase)[[:space:]]*[:=][[:space:]]*["'"'"'][^"'"'"'${}]{8,}'

# A raw 32-byte hex value is an Ethereum private key or seed. Public tx hashes
# and contract addresses are the same shape, so this runs on code only; the
# research notes under docs/ cite real mainnet transactions by hash.
RAWHEX='\b0x[a-fA-F0-9]{64}\b'

# Files that must never be committed, whatever they contain.
BADFILE='\.(key|pem|p12|pfx|jks|keystore|ppk|asc|gpg)$|(^|/)\.env($|\.)|(^|/)id_(rsa|dsa|ecdsa|ed25519)$|(^|/)\.npmrc$|(^|/)\.pypirc$'

# ISO 18013-5 identity fields. This project proves a predicate; it must never
# carry a real person's attributes. Mirrors scripts/pii-scan.sh, applied wider.
MDLPII='(given_name|family_name|birth_date|resident_address|resident_city|resident_postal_code|document_number|portrait|signature_usual_mark|driving_privileges)[[:space:]]*["'"'"']?[[:space:]]*[:=]'

# US SSN and phone shapes.
IDNUM='\b[0-9]{3}-[0-9]{2}-[0-9]{4}\b|\b\(?[0-9]{3}\)?[ .-][0-9]{3}[ .-][0-9]{4}\b'

# --- Allowlist ----------------------------------------------------------------

# fixtures/certs/*.pem are PUBLIC X.509 certificates for the test DMV. A
# certificate is meant to be shared; the matching private key is gitignored and
# regenerated by scripts/gen-test-dmv.sh. The BADFILE rule still rejects .key.
ALLOW_PEM='^fixtures/certs/[A-Za-z0-9._-]+\.pem$'

# Role and team addresses published by their owners as the way to contact them
# (standards bodies, vendor support queues, public mailing lists). Personal
# addresses of named individuals are NOT allowlisted -- cite the person's name
# and the source instead. This repo argues for data minimization; it should not
# republish someone's inbox to make a footnote.
ALLOW_EMAIL='^(info|support|contact|hello|help|press|security|abuse|admin|privacy|legal|noreply|no-reply'
ALLOW_EMAIL+='|identitymangagement|wallet-identity-rp-support|blink-dev|REALID-mDLwaiver'
ALLOW_EMAIL+='|MobileIDHelp'                      # IDEMIA mDL support queue, published on their site
ALLOW_EMAIL+='|[a-z-]+-(dev|discuss|announce|support|request))@'

EMAIL='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}'

# --- Phase 1: working tree ----------------------------------------------------

section "secret-scan phase 1: tracked files"

while IFS= read -r line; do hit "credential: $line"; done < <(
  git grep -InE -e "$CRED" -- . ':!scripts/secret-scan.sh' 2>/dev/null || true )

while IFS= read -r line; do hit "hardcoded secret: $line"; done < <(
  git grep -InE -e "$ASSIGN" -- . ':!scripts/secret-scan.sh' 2>/dev/null || true )

while IFS= read -r line; do hit "raw 32-byte hex (private key or seed?): $line"; done < <(
  git grep -InE -e "$RAWHEX" -- 'packages' 'deploy' 'scripts' 'fixtures' 'bench' 2>/dev/null || true )

while IFS= read -r line; do hit "identity field: $line"; done < <(
  git grep -InE -e "$MDLPII" -- 'packages' 'deploy' 'bench' 2>/dev/null || true )

while IFS= read -r line; do hit "SSN or phone shape: $line"; done < <(
  git grep -InE -e "$IDNUM" -- . ':!scripts/secret-scan.sh' 2>/dev/null || true )

while IFS= read -r f; do
  # A .pem under fixtures/certs/ is allowed only if it holds no private key.
  if printf '%s' "$f" | grep -qE "$ALLOW_PEM" \
     && ! git show "HEAD:$f" 2>/dev/null | grep -q 'PRIVATE KEY'; then
    continue
  fi
  hit "file type must not be committed: $f"
done < <( git ls-files | grep -iE "$BADFILE" || true )

while IFS= read -r line; do
  addr=${line##*:}
  printf '%s' "$addr" | grep -qiE "$ALLOW_EMAIL" && continue
  hit "personal email address: $line"
done < <( git grep -IhoE -e "$EMAIL" -- . ':!scripts/secret-scan.sh' 2>/dev/null | sort -u || true )

# --- Phase 2: full history ----------------------------------------------------

section "secret-scan phase 2: every blob ever committed"

blobs=$(git cat-file --batch-check --batch-all-objects 2>/dev/null | awk '$2=="blob"{print $1}')
count=$(printf '%s\n' "$blobs" | grep -c . || true)
printf '  blobs scanned: %s\n' "$count"

for b in $blobs; do
  found=$(git cat-file blob "$b" 2>/dev/null | grep -aEo -e "$CRED" | sort -u | head -3 || true)
  [ -z "$found" ] && continue
  path=$(git log --all --format='%H' | while read -r c; do
            p=$(git ls-tree -r "$c" 2>/dev/null | awk -v b="$b" '$3==b{print $4; exit}')
            [ -n "$p" ] && { echo "$p"; break; }
          done)
  hit "credential in history: blob $b ${path:+(path: $path)}"
  printf '%s\n' "$found" | sed 's/^/      /'
done

# --- Result -------------------------------------------------------------------

echo
if [ "$fail" -eq 0 ]; then
  echo "secret-scan: clean"
else
  cat <<'MSG'
secret-scan: FAILED

A match is not automatically a leak, but it does not merge until it is
resolved. Pick one:

  * It is a real credential. Rotate it first -- git history is public the
    moment the repo is. Then remove it (git filter-repo) and force-push.
  * It is a personal email address. Cite the person's name and the source
    document instead of their inbox.
  * It is genuinely benign. Add a narrow rule to the ALLOW_* block in
    scripts/secret-scan.sh with a comment saying why.

Do not widen a pattern to make the build pass.
MSG
  exit 1
fi
